jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          wait-on: 'http://localhost:3000'
          record: true
          parallel: true
        env:
          GITHUB_TOKEN_SECRET: ${{ secrets.GITHUB_TOKEN_SECRET }}  # Pasa el token como variable de entorno
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
