name: Run Cypress Tests

# Este flujo se ejecutará cuando haya un push a la rama 'main'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest  # Se utiliza un entorno Linux

    steps:
      # Paso 1: Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v2

      # Paso 2: Configurar Node.js y el entorno
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Usa la versión de Node.js que prefieras

      # Paso 3: Instalar dependencias
      - name: Install dependencies
        run: |
          npm install

      # Paso 4: Ejecutar pruebas de Cypress
      - name: Run Cypress tests
        uses: cypress-io/github-action@v4
        with:
          start: npm start  # Si tienes un servidor de desarrollo que se debe iniciar, reemplázalo por tu comando
          wait-on: 'http://localhost:3000'  # Espera hasta que el servidor esté listo. Cambia el puerto si es necesario.
          wait-on-timeout: 60 # Tiempo de espera para que el servidor esté disponible (en segundos)

      # Paso 5: Mostrar los resultados de Cypress
      - name: Upload Cypress videos and screenshots
        uses: actions/upload-artifact@v3
        with:
          name: cypress-artifacts
          path: |
            cypress/videos
            cypress/screenshots
