describe.skip("Lançamento de boleta", () => {
    it("Lançamento de boleta", () => {
        /* ==== Generated with Cypress Studio ==== */
        cy.visit('http://ourinvest.rf.qa.bankpro.com.br/open/');
        cy.get('form.ng-untouched > .ui-g > :nth-child(2)').click();
        cy.get(':nth-child(2) > core-label > .md-inputfield > .ui-inputtext').type('bankpro_user');
        cy.get('.ng-invalid.ng-dirty > .ui-g > :nth-child(3) > core-label > .md-inputfield > .ui-inputtext').click();
        cy.get('form.ng-dirty > .ui-g > :nth-child(3) > core-label > .md-inputfield > .ui-inputtext').type('topaz');
        cy.get(':nth-child(4) > .ui-button > .ui-button-text').click();
        cy.get('.ui-listbox-list > :nth-child(1)').click();
        cy.get('.card-botoes > .ui-dialog-buttonpane > .ui-button > .ui-button-text').click();
        cy.get(':nth-child(3) > .card > a > h2').click();
        cy.get(':nth-child(1) > .botao-novo > .ui-button-icon-left').click();
        cy.get(':nth-child(2) > ope-tipooperacao > .padrao-campos > .tipo-operacao > .md-inputfield > .ng-untouched > .tipoOperacao').click();
        cy.get('.ui-dropdown-items > :nth-child(2)').click();
        cy.get('.clearing > ope-clearings > .padrao-campos > .clearings > .md-inputfield > .ng-untouched > .ui-dropdown').click();
        cy.get('.ui-dropdown-items > :nth-child(3) > span').click();
        cy.get('.pull-right > .botao-novo > .ui-button-text').click();
        cy.get('#idContraParte > core-adv-search > .button-search > blockable-div > .blockable-div > .busca-avancada > .md-inputfield > .ui-inputtext').clear('B');
        cy.get('#idContraParte > core-adv-search > .button-search > blockable-div > .blockable-div > .busca-avancada > .md-inputfield > .ui-inputtext').type('BA');
        cy.get('.pesquisa-cliente').clear();
        cy.get('.pesquisa-cliente').type('BANCO OURINVEST');
        cy.get('[style="display: block; min-width: 150px; z-index: 1037; left: 77px; top: 150.5px; opacity: 1;"] > .ui-dialog-content > p-fieldset > .ui-fieldset > .ui-fieldset-content-wrapper > .ui-fieldset-content > .ui-g-3 > :nth-child(2) > .botao-adv-search-superior > .ui-button-text').click();
        cy.get('#idTituloSearch > core-adv-search > .button-search > blockable-div > .blockable-div > .busca-avancada > .md-inputfield > .ui-inputtext').clear('L');
        cy.get('#idTituloSearch > core-adv-search > .button-search > blockable-div > .blockable-div > .busca-avancada > .md-inputfield > .ui-inputtext').type('LO');
        cy.get('[search-body=""] > :nth-child(1) > core-label > .md-inputfield > .ng-untouched').clear();
        cy.get('[search-body=""] > :nth-child(1) > core-label > .md-inputfield > .ng-untouched').type('LORTB2');
        cy.get('[style="display: block; min-width: 150px; z-index: 1042; left: 77px; top: 150.5px; opacity: 1;"] > .ui-dialog-content > p-fieldset > .ui-fieldset > .ui-fieldset-content-wrapper > .ui-fieldset-content > .ui-g-3 > :nth-child(2) > .botao-adv-search-superior > .ui-button-icon-left').click();
        cy.get('.button-search > core-label > .md-inputfield > .ng-untouched').clear('1');
        cy.get('.button-search > core-label > .md-inputfield > .ng-untouched').type('10');
        cy.get('.ui-g-12 > :nth-child(2) > core-label > .md-inputfield > .ui-inputtext').clear('1');
        cy.get('.ui-g-12 > :nth-child(2) > core-label > .md-inputfield > .ui-inputtext').type('100');
        cy.get('.ng-untouched > .classificacao').click();
        cy.get('.ui-dropdown-items > :nth-child(2)').click();
        cy.get('.modelo_negocio > .ui-dropdown-trigger > .fa').click();
        cy.get('.modelo_negocio > .ui-dropdown-trigger > .fa').click();
        cy.get('.ng-untouched > .liquidacao').click();
        cy.get('.ui-dropdown-items > :nth-child(3)').click();
        cy.get('.ui-fieldset-content > .ng-untouched').click();
        cy.get('footer > .card-botoes > :nth-child(1) > .ui-button > .ui-button-text').click();
        cy.get(':nth-child(1) > .botao-novo > .ui-button-icon-left').click();
        cy.get(':nth-child(2) > ope-tipooperacao > .padrao-campos > .tipo-operacao > .md-inputfield > .ng-valid > .tipoOperacao').click();
        cy.get('.ui-dropdown-items > :nth-child(10) > span').click();
        cy.get('.clearing > ope-clearings > .padrao-campos > .clearings > .md-inputfield > .ng-valid > .ui-dropdown').click();
        cy.get('.ui-dropdown-items > :nth-child(2)').click();
        cy.get('.pull-right > .botao-novo > .ui-button-text').click();
        cy.get('#idContraParte > core-adv-search > .button-search > blockable-div > .blockable-div > .busca-avancada > .md-inputfield > .ui-inputtext').clear('B');
        cy.get('#idContraParte > core-adv-search > .button-search > blockable-div > .blockable-div > .busca-avancada > .md-inputfield > .ui-inputtext').type('BA');
        cy.get('.pesquisa-cliente').clear();
        cy.get('.pesquisa-cliente').type('BANCO OURINVEST');
        cy.get('[style="display: block; min-width: 150px; z-index: 1084; left: 77px; top: 150.5px; opacity: 1;"] > .ui-dialog-content > p-fieldset > .ui-fieldset > .ui-fieldset-content-wrapper > .ui-fieldset-content > .ui-g-3 > :nth-child(2) > .botao-adv-search-superior > .ui-button-icon-left').click();
        cy.get('#idTituloSearch > core-adv-search > .button-search > blockable-div > .blockable-div > .busca-avancada > .md-inputfield > .ui-inputtext').clear('2');
        cy.get('#idTituloSearch > core-adv-search > .button-search > blockable-div > .blockable-div > .busca-avancada > .md-inputfield > .ui-inputtext').type('21');
        cy.get('[search-body=""] > :nth-child(1) > core-label > .md-inputfield > .ng-untouched').clear();
        cy.get('[search-body=""] > :nth-child(1) > core-label > .md-inputfield > .ng-untouched').type('210100');
        cy.get('[style="display: block; min-width: 150px; z-index: 1090; left: 77px; top: 150.5px; opacity: 1;"] > .ui-dialog-content > p-fieldset > .ui-fieldset > .ui-fieldset-content-wrapper > .ui-fieldset-content > .ui-g-3 > :nth-child(2) > .botao-adv-search-superior > .ui-button-text').click();
        cy.get('.ui-paginator-pages > :nth-child(2)').click();
        cy.get('.ui-datatable-data > :nth-child(3) > :nth-child(1)').click();
        cy.get('[style="display: block; min-width: 150px; z-index: 1097; left: 77px; top: 150.5px; opacity: 1;"] > .ui-dialog-content > .ui-g-12 > .card-botoes > :nth-child(1) > .botao-adv-search > .ui-button-text').click();
        cy.get('.button-search > core-label > .md-inputfield > .ng-untouched').clear('01');
        cy.get('.button-search > core-label > .md-inputfield > .ng-untouched').type('010');
        cy.get('[legend="Operação"] > .ui-fieldset > .ui-fieldset-content-wrapper > .ui-fieldset-content > :nth-child(2) > core-label > .md-inputfield > .ui-inputtext').clear('1');
        cy.get('[legend="Operação"] > .ui-fieldset > .ui-fieldset-content-wrapper > .ui-fieldset-content > :nth-child(2) > core-label > .md-inputfield > .ui-inputtext').type('100');
        cy.get('.ng-untouched > .classificacao').click();
        cy.get('.ui-dropdown-items > :nth-child(2)').click();
        cy.get('.ui-fieldset-content > .ng-untouched').click();
        cy.get('footer > .card-botoes > :nth-child(1) > .ui-button > .ui-button-icon-left').click();
        cy.get(':nth-child(1) > .botao-novo > .ui-button-icon-left').click();
        cy.get('.negocioCombo').click();
        cy.get('.ui-dropdown-items > :nth-child(2) > span').click();
        cy.get(':nth-child(2) > ope-tipooperacao > .padrao-campos > .tipo-operacao > .md-inputfield > .ng-valid > .tipoOperacao').click();
        cy.get('.ui-dropdown-items > :nth-child(6) > span').click();
        cy.get('.clearing > ope-clearings > .padrao-campos > .clearings > .md-inputfield > .ng-valid > .ui-dropdown > .ui-dropdown-trigger > .fa').click();
        cy.get('.ui-dropdown-items > :nth-child(2) > span').click();
        cy.get('.pull-right > .botao-novo > .ui-button-text').click();
        cy.get('#idContraParte > core-adv-search > .button-search > blockable-div > .blockable-div > .busca-avancada > .md-inputfield > .ui-inputtext').clear('b');
        cy.get('#idContraParte > core-adv-search > .button-search > blockable-div > .blockable-div > .busca-avancada > .md-inputfield > .ui-inputtext').type('b');
        cy.get('.pesquisa-cliente').clear('b');
        cy.get('.pesquisa-cliente').type('bANCO OURINVEST');
        cy.get('[style="display: block; min-width: 150px; z-index: 1140; left: 77px; top: 150.5px; opacity: 1;"] > .ui-dialog-content > p-fieldset > .ui-fieldset > .ui-fieldset-content-wrapper > .ui-fieldset-content > .ui-g-3 > :nth-child(2) > .botao-adv-search-superior').click();
        cy.get('#idTituloSearch > core-adv-search > .button-search > blockable-div > .blockable-div > .busca-avancada > .md-inputfield > .ui-inputtext').clear('1');
        cy.get('#idTituloSearch > core-adv-search > .button-search > blockable-div > .blockable-div > .busca-avancada > .md-inputfield > .ui-inputtext').type('10');
        cy.get('[style="display: block; min-width: 150px; z-index: 1148; left: 77px; top: 150.5px; opacity: 1;"] > .ui-dialog-content > p-fieldset > .ui-fieldset > .ui-fieldset-content-wrapper > .ui-fieldset-content > .ui-g-9 > [search-body=""] > :nth-child(1) > core-label > .md-inputfield > .ng-untouched').clear();
        cy.get('[style="display: block; min-width: 150px; z-index: 1148; left: 77px; top: 150.5px; opacity: 1;"] > .ui-dialog-content > p-fieldset > .ui-fieldset > .ui-fieldset-content-wrapper > .ui-fieldset-content > .ui-g-9 > [search-body=""] > :nth-child(1) > core-label > .md-inputfield > .ng-untouched').type('100000');
        cy.get('[style="display: block; min-width: 150px; z-index: 1148; left: 77px; top: 150.5px; opacity: 1;"] > .ui-dialog-content > p-fieldset > .ui-fieldset > .ui-fieldset-content-wrapper > .ui-fieldset-content > .ui-g-3 > :nth-child(2) > .botao-adv-search-superior > .ui-button-icon-left').click();
        cy.get('.ui-datatable-data > :nth-child(7) > :nth-child(3)').click();
        cy.get('[style="display: block; min-width: 150px; z-index: 1152; left: 77px; top: 150.5px; opacity: 1;"] > .ui-dialog-content > .ui-g-12 > .card-botoes > :nth-child(1) > .botao-adv-search > .ui-button-text').click();
        cy.get('.ui-fieldset-content > :nth-child(1) > core-label > .md-inputfield > .ui-inputtext').clear('1');
        cy.get('.ui-fieldset-content > :nth-child(1) > core-label > .md-inputfield > .ui-inputtext').type('100');
        cy.get('[legend="Operação"] > .ui-fieldset').click();
        cy.get(':nth-child(6) > core-label > .md-inputfield > .ui-inputtext').clear('01');
        cy.get(':nth-child(6) > core-label > .md-inputfield > .ui-inputtext').type('010');
        cy.get('.ng-untouched > .classificacao').click();
        cy.get('.ui-dropdown-items > :nth-child(2)').click();
        cy.get('.ui-fieldset-content > .ng-untouched').click();
        cy.get('footer > .card-botoes > :nth-child(1) > .ui-button > .ui-button-icon-left').click();
        cy.get(':nth-child(1) > .botao-novo > .ui-button-icon-left').click();
        cy.get('.negocioCombo').click();
        cy.get('.ui-dropdown-items > :nth-child(4) > span').click();
        cy.get(':nth-child(2) > ope-tipooperacao > .padrao-campos > .tipo-operacao > .md-inputfield > .ng-valid > .tipoOperacao').click();
        cy.get('.ui-dropdown-items > :nth-child(10) > span').click();
        cy.get('.clearing > ope-clearings > .padrao-campos > .clearings > .md-inputfield > .ng-valid > .ui-dropdown').click();
        cy.get('.ui-dropdown-items > :nth-child(3) > span').click();
        cy.get('.pull-right > .botao-novo > .ui-button-text').click();
        cy.get('#idContraParte > core-adv-search > .button-search > blockable-div > .blockable-div > .busca-avancada > .md-inputfield > .ui-inputtext').clear('B');
        cy.get('#idContraParte > core-adv-search > .button-search > blockable-div > .blockable-div > .busca-avancada > .md-inputfield > .ui-inputtext').type('BA');
        cy.get('[style="display: block; min-width: 150px; z-index: 1199; left: 77px; top: 150.5px; opacity: 1;"] > .ui-dialog-content > p-fieldset > .ui-fieldset > .ui-fieldset-content-wrapper > .ui-fieldset-content > .ui-g-9 > .ui-g > .pull-left > core-label > .md-inputfield > .pesquisa-cliente').clear();
        cy.get('[style="display: block; min-width: 150px; z-index: 1199; left: 77px; top: 150.5px; opacity: 1;"] > .ui-dialog-content > p-fieldset > .ui-fieldset > .ui-fieldset-content-wrapper > .ui-fieldset-content > .ui-g-9 > .ui-g > .pull-left > core-label > .md-inputfield > .pesquisa-cliente').type('BANCO OURINVEST');
        cy.get('[style="display: block; min-width: 150px; z-index: 1199; left: 77px; top: 150.5px; opacity: 1;"] > .ui-dialog-content > p-fieldset > .ui-fieldset > .ui-fieldset-content-wrapper > .ui-fieldset-content > .ui-g-3 > :nth-child(2) > .botao-adv-search-superior > .ui-button-text').click();
        cy.get('#idInstituicaoFinanceira > core-adv-search > .button-search > blockable-div > .blockable-div > .busca-avancada > .md-inputfield > .ui-inputtext').clear('L');
        cy.get('#idInstituicaoFinanceira > core-adv-search > .button-search > blockable-div > .blockable-div > .busca-avancada > .md-inputfield > .ui-inputtext').type('LO');
        cy.get('.ng-animating > .ui-dialog-content > p-fieldset > .ui-fieldset > .ui-fieldset-content-wrapper > .ui-fieldset-content > .ui-g-9 > .ui-g > .pull-left > core-label > .md-inputfield > .pesquisa-cliente').clear();
        cy.get('.ng-animating > .ui-dialog-content > p-fieldset > .ui-fieldset > .ui-fieldset-content-wrapper > .ui-fieldset-content > .ui-g-9 > .ui-g > .pull-left > core-label > .md-inputfield > .pesquisa-cliente').type('LORB');
        cy.get('[style="display: block; min-width: 150px; z-index: 1207; left: 77px; top: 150.5px; opacity: 1;"] > .ui-dialog-content > p-fieldset > .ui-fieldset > .ui-fieldset-content-wrapper > .ui-fieldset-content > .ui-g-9 > .ui-g > .pull-left > core-label > .md-inputfield > .pesquisa-cliente').clear();
        cy.get('[style="display: block; min-width: 150px; z-index: 1207; left: 77px; top: 150.5px; opacity: 1;"] > .ui-dialog-content > p-fieldset > .ui-fieldset > .ui-fieldset-content-wrapper > .ui-fieldset-content > .ui-g-9 > .ui-g > .pull-left > core-label > .md-inputfield > .pesquisa-cliente').type('LORTB2');
        cy.get('[style="display: block; min-width: 150px; z-index: 1207; left: 77px; top: 150.5px; opacity: 1;"] > .ui-dialog-content > p-fieldset > .ui-fieldset > .ui-fieldset-content-wrapper > .ui-fieldset-content > .ui-g-3 > :nth-child(2) > .botao-adv-search-superior > .ui-button-icon-left').click();
        cy.get('[style="display: block; min-width: 150px; z-index: 1208; left: 77px; top: 150.5px; opacity: 1;"] > .ui-dialog-content > p-fieldset > .ui-fieldset > .ui-fieldset-content-wrapper > .ui-fieldset-content > .ui-g-9 > .ui-g > .pull-left > core-label > .md-inputfield > .pesquisa-cliente').click();
        cy.get('[style="display: block; min-width: 150px; z-index: 1211; left: 77px; top: 150.5px; opacity: 1;"] > .ui-dialog-content > p-fieldset > .ui-fieldset > .ui-fieldset-content-wrapper > .ui-fieldset-content > .ui-g-9 > .ui-g > .pull-left > core-label > .md-inputfield > .pesquisa-cliente').click();
        cy.get('[style="display: block; min-width: 150px; z-index: 1212; left: 77px; top: 150.5px; opacity: 1;"] > .ui-dialog-content > p-fieldset > .ui-fieldset > .ui-fieldset-content-wrapper > .ui-fieldset-content > .ui-g-9 > .ui-g > .pull-left > core-label > .md-inputfield > .pesquisa-cliente').clear();
        cy.get('[style="display: block; min-width: 150px; z-index: 1212; left: 77px; top: 150.5px; opacity: 1;"] > .ui-dialog-content > p-fieldset > .ui-fieldset > .ui-fieldset-content-wrapper > .ui-fieldset-content > .ui-g-9 > .ui-g > .pull-left > core-label > .md-inputfield > .pesquisa-cliente').type('210100');
        cy.get('[style="display: block; min-width: 150px; z-index: 1212; left: 77px; top: 150.5px; opacity: 1;"] > .ui-dialog-content > p-fieldset > .ui-fieldset > .ui-fieldset-content-wrapper > .ui-fieldset-content > .ui-g-3 > :nth-child(2) > .botao-adv-search-superior > .ui-button-icon-left').click();
        cy.get('[style="display: block; min-width: 150px; z-index: 1213; left: 77px; top: 150.5px; opacity: 1;"] > .ui-dialog-content > p-fieldset > .ui-fieldset > .ui-fieldset-content-wrapper > .ui-fieldset-content > .ui-g-9 > .ui-g > .pull-left > core-label > .md-inputfield > .pesquisa-cliente').click();
        cy.get('[style="display: block; min-width: 150px; z-index: 1216; left: 77px; top: 150.5px; opacity: 1;"] > .ui-dialog-content > p-fieldset > .ui-fieldset > .ui-fieldset-content-wrapper > .ui-fieldset-content > .ui-g-9 > .ui-g > .pull-left > core-label > .md-inputfield > .pesquisa-cliente').click();
        cy.get('[style="display: block; min-width: 150px; z-index: 1217; left: 77px; top: 150.5px; opacity: 1;"] > .ui-dialog-content > p-fieldset > .ui-fieldset > .ui-fieldset-content-wrapper > .ui-fieldset-content > .ui-g-3 > :nth-child(2) > .botao-adv-search-superior > .ui-button-text').click();
        cy.get('[icon="ui-icon-highlight-off"] > .ui-button-text').click();
        cy.get('[style="display: block; min-width: 150px; z-index: 1218; left: 77px; top: 150.5px; opacity: 1;"] > .ui-dialog-content > .ui-g-12 > .card-botoes > :nth-child(2) > .botao-adv-search > .ui-button-text').click();
        cy.get('footer > .card-botoes > :nth-child(2) > .ui-button > .ui-button-text').click();
        cy.get(':nth-child(1) > .botao-novo > .ui-button-icon-left').click();
        cy.get('.negocioCombo').click();
        cy.get('.ui-dropdown-items > :nth-child(2) > span').click();
        cy.get(':nth-child(2) > ope-tipooperacao > .padrao-campos > .tipo-operacao > .md-inputfield > .ng-valid > .tipoOperacao').click();
        cy.get('.ui-dropdown-items > :nth-child(8) > span').click();
        cy.get('.clearing > ope-clearings > .padrao-campos > .clearings > .md-inputfield > .ng-valid > .ui-dropdown').click();
        cy.get('.ui-dropdown-items > :nth-child(2)').click();
        cy.get('.pull-right > .botao-novo > .ui-button-icon-left').click();
        cy.get('#idContraParte > core-adv-search > .button-search > blockable-div > .blockable-div > .busca-avancada > .md-inputfield > .ui-inputtext').clear('B');
        cy.get('#idContraParte > core-adv-search > .button-search > blockable-div > .blockable-div > .busca-avancada > .md-inputfield > .ui-inputtext').type('BA');
        cy.get('.pesquisa-cliente').clear();
        cy.get('.pesquisa-cliente').type('BANCO OURINVEST');
        cy.get('[style="display: block; min-width: 150px; z-index: 1249; left: 77px; top: 150.5px; opacity: 1;"] > .ui-dialog-content > p-fieldset > .ui-fieldset > .ui-fieldset-content-wrapper > .ui-fieldset-content > .ui-g-3 > :nth-child(2) > .botao-adv-search-superior > .ui-button-text').click();
        cy.get('.ui-fieldset-content > :nth-child(1) > core-label > .md-inputfield > .ui-inputtext').clear('0,01');
        cy.get('.ui-fieldset-content > :nth-child(1) > core-label > .md-inputfield > .ui-inputtext').type('10,00');
        cy.get('.ui-fieldset-content > :nth-child(5) > core-label > .md-inputfield > .ui-inputtext').clear('10');
        cy.get('.ui-fieldset-content > :nth-child(5) > core-label > .md-inputfield > .ui-inputtext').type('10');
        cy.get(':nth-child(6) > core-label > .md-inputfield > .ui-inputtext').clear('01');
        cy.get(':nth-child(6) > core-label > .md-inputfield > .ui-inputtext').type('10');
        cy.get('#idTituloSearch > core-adv-search > .button-search > blockable-div > .blockable-div > .busca-avancada > .md-inputfield > .ui-inputtext').clear('1');
        cy.get('#idTituloSearch > core-adv-search > .button-search > blockable-div > .blockable-div > .busca-avancada > .md-inputfield > .ui-inputtext').type('10');
        cy.get('[search-body=""] > :nth-child(1) > core-label > .md-inputfield > .ng-untouched').clear();
        cy.get('[search-body=""] > :nth-child(1) > core-label > .md-inputfield > .ng-untouched').type('100000');
        cy.get('[style="display: block; min-width: 150px; z-index: 1258; left: 77px; top: 150.5px; opacity: 1;"] > .ui-dialog-content > p-fieldset > .ui-fieldset > .ui-fieldset-content-wrapper > .ui-fieldset-content > .ui-g-3 > :nth-child(2) > .botao-adv-search-superior > .ui-button-icon-left').click();
        cy.get(':nth-child(8) > :nth-child(4) > .ui-cell-data > :nth-child(2) > span').click();
        cy.get('[style="display: block; min-width: 150px; z-index: 1262; left: 77px; top: 150.5px; opacity: 1;"] > .ui-dialog-content > .ui-g-12 > .card-botoes > :nth-child(1) > .botao-adv-search > .ui-button-text').click();
        cy.get('[legend="Lastro específico "] > .ui-fieldset > .ui-fieldset-content-wrapper > .ui-fieldset-content > :nth-child(2) > core-label > .md-inputfield > .ui-inputtext').clear('1');
        cy.get('[legend="Lastro específico "] > .ui-fieldset > .ui-fieldset-content-wrapper > .ui-fieldset-content > :nth-child(2) > core-label > .md-inputfield > .ui-inputtext').type('100');
        cy.get('.ng-untouched > .classificacao').click();
        cy.get('.ui-dropdown-items > :nth-child(2)').click();
        cy.get('.ui-fieldset-content > .ng-untouched').click();
        cy.get('footer > .card-botoes > :nth-child(1) > .ui-button > .ui-button-text').click();
        cy.get('[icon="ui-icon-highlight-off"] > .ui-button-text').click();
        cy.get('.campo-rotina-calculo > .md-inputfield > .ng-untouched > .ui-dropdown').click();
        cy.get('.ui-dropdown-items > :nth-child(4)').click();
        cy.get('footer > .card-botoes > :nth-child(1) > .ui-button > .ui-button-text').click();
        cy.get('[icon="ui-icon-highlight-off"] > .ui-button-icon-left').click();
        cy.get('.ui-fieldset-content > :nth-child(5) > core-label > .md-inputfield > .ui-inputtext').clear('1');
        cy.get('.ui-fieldset-content > :nth-child(5) > core-label > .md-inputfield > .ui-inputtext').type('10');
        cy.get('footer > .card-botoes > :nth-child(1) > .ui-button > .ui-button-icon-left').click();
        cy.get(':nth-child(1) > .botao-novo > .ui-button-icon-left').click();
        cy.get('.negocioCombo').click();
        cy.get('.ui-dropdown-items > :nth-child(1)').click();
        cy.get(':nth-child(2) > ope-tipooperacao > .padrao-campos > .tipo-operacao > .md-inputfield > .ng-valid > .tipoOperacao').click();
        cy.get(':nth-child(14) > span').click();
        cy.get('.clearing > ope-clearings > .padrao-campos > .clearings > .md-inputfield > .ng-valid > .ui-dropdown').click();
        cy.get('.ui-dropdown-items > :nth-child(2) > span').click();
        cy.get('.pull-right > .botao-novo > .ui-button-text').click();
        cy.get('#idContraParte > core-adv-search > .button-search > blockable-div > .blockable-div > .busca-avancada > .md-inputfield > .ui-inputtext').clear('B');
        cy.get('#idContraParte > core-adv-search > .button-search > blockable-div > .blockable-div > .busca-avancada > .md-inputfield > .ui-inputtext').type('BA');
        cy.get('.pesquisa-cliente').clear();
        cy.get('.pesquisa-cliente').type('BANCO OURINVEST');
        cy.get('[style="display: block; min-width: 150px; z-index: 1311; left: 77px; top: 150.5px; opacity: 1;"] > .ui-dialog-content > p-fieldset > .ui-fieldset > .ui-fieldset-content-wrapper > .ui-fieldset-content > .ui-g-3 > :nth-child(2) > .botao-adv-search-superior > .ui-button-text').click();
        cy.get('.ui-fieldset-content > :nth-child(1) > core-label > .md-inputfield > .ui-inputtext').clear('0,01');
        cy.get('.ui-fieldset-content > :nth-child(1) > core-label > .md-inputfield > .ui-inputtext').type('10,00');
        cy.get('.campo-rotina-calculo > .md-inputfield > .ng-untouched > .ui-dropdown').click();
        cy.get('.ui-dropdown-items > :nth-child(4)').click();
        cy.get('.ui-fieldset-content > :nth-child(5) > core-label > .md-inputfield > .ui-inputtext').clear('1');
        cy.get('.ui-fieldset-content > :nth-child(5) > core-label > .md-inputfield > .ui-inputtext').type('10');
        cy.get(':nth-child(6) > core-label > .md-inputfield > .ui-inputtext').clear('01');
        cy.get(':nth-child(6) > core-label > .md-inputfield > .ui-inputtext').type('10');
        cy.get('#idTituloSearch > core-adv-search > .button-search > blockable-div > .blockable-div > .busca-avancada > .md-inputfield > .ui-inputtext').clear('2');
        cy.get('#idTituloSearch > core-adv-search > .button-search > blockable-div > .blockable-div > .busca-avancada > .md-inputfield > .ui-inputtext').type('21');
        cy.get('[search-body=""] > :nth-child(1) > core-label > .md-inputfield > .ng-untouched').clear();
        cy.get('[search-body=""] > :nth-child(1) > core-label > .md-inputfield > .ng-untouched').type('210100');
        cy.get('[style="display: block; min-width: 150px; z-index: 1322; left: 77px; top: 150.5px; opacity: 1;"] > .ui-dialog-content > p-fieldset > .ui-fieldset > .ui-fieldset-content-wrapper > .ui-fieldset-content > .ui-g-3 > :nth-child(2) > .botao-adv-search-superior > .ui-button-text').click();
        cy.get('.ui-datatable-data > :nth-child(9) > :nth-child(3)').click();
        cy.get('[style="display: block; min-width: 150px; z-index: 1326; left: 77px; top: 150.5px; opacity: 1;"] > .ui-dialog-content > .ui-g-12 > .card-botoes > :nth-child(1) > .botao-adv-search > .ui-button-text').click();
        cy.get('[legend="Lastro específico "] > .ui-fieldset > .ui-fieldset-content-wrapper > .ui-fieldset-content > :nth-child(2) > core-label > .md-inputfield > .ui-inputtext').clear('1');
        cy.get('[legend="Lastro específico "] > .ui-fieldset > .ui-fieldset-content-wrapper > .ui-fieldset-content > :nth-child(2) > core-label > .md-inputfield > .ui-inputtext').type('10');
        cy.get('.ng-untouched > .classificacao').click();
        cy.get('.ui-dropdown-items > :nth-child(2)').click();
        cy.get('.ui-fieldset-content > .ng-untouched').click();
        cy.get('footer > .card-botoes > :nth-child(1) > .ui-button > .ui-button-text').click();
        cy.get(':nth-child(1) > .botao-novo > .ui-button-icon-left').click();
        cy.get('.negocioCombo').click();
        cy.get('.ui-dropdown-items > :nth-child(2)').click();
        cy.get(':nth-child(2) > ope-tipooperacao > .padrao-campos > .tipo-operacao > .md-inputfield > .ng-valid > .tipoOperacao').click();
        cy.get(':nth-child(18) > span').click();
        cy.get('.clearing > ope-clearings > .padrao-campos > .clearings > .md-inputfield > .ng-valid > .ui-dropdown > .ui-dropdown-trigger > .fa').click();
        cy.get('.ui-dropdown-items > :nth-child(3) > span').click();
        cy.get('.pull-right > .botao-novo > .ui-button-text').click();
        cy.get('#idContraParte > core-adv-search > .button-search > blockable-div > .blockable-div > .busca-avancada > .md-inputfield > .ui-inputtext').clear('B');
        cy.get('#idContraParte > core-adv-search > .button-search > blockable-div > .blockable-div > .busca-avancada > .md-inputfield > .ui-inputtext').type('BA');
        cy.get('.pesquisa-cliente').clear();
        cy.get('.pesquisa-cliente').type('BANCO OURINVEST');
        cy.get('[style="display: block; min-width: 150px; z-index: 1364; left: 77px; top: 150.5px; opacity: 1;"] > .ui-dialog-content > p-fieldset > .ui-fieldset > .ui-fieldset-content-wrapper > .ui-fieldset-content > .ui-g-3 > :nth-child(2) > .botao-adv-search-superior > .ui-button-text').click();
        cy.get('.ui-fieldset-content > :nth-child(1) > core-label > .md-inputfield > .ui-inputtext').clear('0,01');
        cy.get('.ui-fieldset-content > :nth-child(1) > core-label > .md-inputfield > .ui-inputtext').type('10,00');
        cy.get('.campo-rotina-calculo > .md-inputfield > .ng-untouched > .ui-dropdown > .ui-dropdown-trigger > .fa').click();
        cy.get('.ui-dropdown-items > :nth-child(4)').click();
        cy.get('.ui-fieldset-content > :nth-child(5) > core-label > .md-inputfield > .ui-inputtext').clear('1');
        cy.get('.ui-fieldset-content > :nth-child(5) > core-label > .md-inputfield > .ui-inputtext').type('10');
        cy.get(':nth-child(6) > core-label > .md-inputfield > .ui-inputtext').clear('01');
        cy.get(':nth-child(6) > core-label > .md-inputfield > .ui-inputtext').type('10');
        cy.get('#idTituloSearch > core-adv-search > .button-search > blockable-div > .blockable-div > .busca-avancada > .md-inputfield > .ui-inputtext').clear('L');
        cy.get('#idTituloSearch > core-adv-search > .button-search > blockable-div > .blockable-div > .busca-avancada > .md-inputfield > .ui-inputtext').type('LO');
        cy.get('[search-body=""] > :nth-child(1) > core-label > .md-inputfield > .ng-untouched').clear();
        cy.get('[search-body=""] > :nth-child(1) > core-label > .md-inputfield > .ng-untouched').type('LORTB2');
        cy.get('[style="display: block; min-width: 150px; z-index: 1374; left: 77px; top: 150.5px; opacity: 1;"] > .ui-dialog-content > p-fieldset > .ui-fieldset > .ui-fieldset-content-wrapper > .ui-fieldset-content > .ui-g-3 > :nth-child(2) > .botao-adv-search-superior > .ui-button-text').click();
        cy.get('[legend="Lastro específico "] > .ui-fieldset > .ui-fieldset-content-wrapper > .ui-fieldset-content > :nth-child(2) > core-label > .md-inputfield > .ui-inputtext').clear('1');
        cy.get('[legend="Lastro específico "] > .ui-fieldset > .ui-fieldset-content-wrapper > .ui-fieldset-content > :nth-child(2) > core-label > .md-inputfield > .ui-inputtext').type('10');
        cy.get('.ng-untouched > .classificacao').click();
        cy.get('.ui-dropdown-items > :nth-child(2) > span').click();
        cy.get('.ui-fieldset-content > .ng-untouched').click();
        cy.get('footer > .card-botoes > :nth-child(1) > .ui-button > .ui-button-text').click();
        cy.get(':nth-child(1) > .botao-novo > .ui-button-icon-left').click();
        cy.get('.negocioCombo').click();
        cy.get('.ui-dropdown-items > :nth-child(4) > span').click();
        cy.get(':nth-child(2) > ope-tipooperacao > .padrao-campos > .tipo-operacao > .md-inputfield > .ng-valid > .tipoOperacao').click();
        cy.get('.ui-dropdown-items > :nth-child(3) > span').click();
        cy.get('.clearing > ope-clearings > .padrao-campos > .clearings > .md-inputfield > .ng-valid > .ui-dropdown').click();
        cy.get('.ui-dropdown-items > :nth-child(3) > span').click();
        cy.get('.pull-right > .botao-novo > .ui-button-text').click();
        cy.get('#idContraParte > core-adv-search > .button-search > blockable-div > .blockable-div > .busca-avancada > .md-inputfield > .ui-inputtext').clear('B');
        cy.get('#idContraParte > core-adv-search > .button-search > blockable-div > .blockable-div > .busca-avancada > .md-inputfield > .ui-inputtext').type('BA');
        cy.get('.ng-animating > .ui-dialog-content > p-fieldset > .ui-fieldset > .ui-fieldset-content-wrapper > .ui-fieldset-content > .ui-g-9 > .ui-g > .pull-left > core-label > .md-inputfield > .pesquisa-cliente').clear();
        cy.get('.ng-animating > .ui-dialog-content > p-fieldset > .ui-fieldset > .ui-fieldset-content-wrapper > .ui-fieldset-content > .ui-g-9 > .ui-g > .pull-left > core-label > .md-inputfield > .pesquisa-cliente').type('BANCO OUR');
        cy.get('[style="display: block; min-width: 150px; z-index: 1417; left: 77px; top: 150.5px; opacity: 1;"] > .ui-dialog-content > p-fieldset > .ui-fieldset > .ui-fieldset-content-wrapper > .ui-fieldset-content > .ui-g-9 > .ui-g > .pull-left > core-label > .md-inputfield > .pesquisa-cliente').clear();
        cy.get('[style="display: block; min-width: 150px; z-index: 1417; left: 77px; top: 150.5px; opacity: 1;"] > .ui-dialog-content > p-fieldset > .ui-fieldset > .ui-fieldset-content-wrapper > .ui-fieldset-content > .ui-g-9 > .ui-g > .pull-left > core-label > .md-inputfield > .pesquisa-cliente').type('BANCO OURINVEST');
        cy.get('[style="display: block; min-width: 150px; z-index: 1417; left: 77px; top: 150.5px; opacity: 1;"] > .ui-dialog-content > p-fieldset > .ui-fieldset > .ui-fieldset-content-wrapper > .ui-fieldset-content > .ui-g-3 > :nth-child(2) > .botao-adv-search-superior > .ui-button-text').click();
        cy.get('#idTituloSearch > core-adv-search > .button-search > blockable-div > .blockable-div > .busca-avancada > .md-inputfield > .ui-inputtext').clear('L');
        cy.get('#idTituloSearch > core-adv-search > .button-search > blockable-div > .blockable-div > .busca-avancada > .md-inputfield > .ui-inputtext').type('LO');
        cy.get('.ng-animating > .ui-dialog-content > p-fieldset > .ui-fieldset > .ui-fieldset-content-wrapper > .ui-fieldset-content > .ui-g-9 > [search-body=""] > :nth-child(1) > core-label > .md-inputfield > .ng-untouched').clear();
        cy.get('.ng-animating > .ui-dialog-content > p-fieldset > .ui-fieldset > .ui-fieldset-content-wrapper > .ui-fieldset-content > .ui-g-9 > [search-body=""] > :nth-child(1) > core-label > .md-inputfield > .ng-untouched').type('LORTB');
        cy.get('[style="display: block; min-width: 150px; z-index: 1422; left: 77px; top: 150.5px; opacity: 1;"] > .ui-dialog-content > p-fieldset > .ui-fieldset > .ui-fieldset-content-wrapper > .ui-fieldset-content > .ui-g-9 > [search-body=""] > :nth-child(1) > core-label > .md-inputfield > .ng-untouched').clear();
        cy.get('[style="display: block; min-width: 150px; z-index: 1422; left: 77px; top: 150.5px; opacity: 1;"] > .ui-dialog-content > p-fieldset > .ui-fieldset > .ui-fieldset-content-wrapper > .ui-fieldset-content > .ui-g-9 > [search-body=""] > :nth-child(1) > core-label > .md-inputfield > .ng-untouched').type('LORTB2');
        cy.get('[style="display: block; min-width: 150px; z-index: 1422; left: 77px; top: 150.5px; opacity: 1;"] > .ui-dialog-content > p-fieldset > .ui-fieldset > .ui-fieldset-content-wrapper > .ui-fieldset-content > .ui-g-3 > :nth-child(2) > .botao-adv-search-superior > .ui-button-icon-left').click();
        cy.get('.button-search > core-label > .md-inputfield > .ng-untouched').clear('1');
        cy.get('.button-search > core-label > .md-inputfield > .ng-untouched').type('100');
        cy.get('.campo-rotina-calculo > .md-inputfield > .ng-untouched > .ui-dropdown').click();
        cy.get('.campo-rotina-calculo > .md-inputfield > .ng-untouched > .ui-dropdown > .ui-dropdown-trigger > .fa').click();
        cy.get('.ui-fieldset-content > :nth-child(1) > core-label > .md-inputfield > .ui-inputtext').clear('1');
        cy.get('.ui-fieldset-content > :nth-child(1) > core-label > .md-inputfield > .ui-inputtext').type('10');
        cy.get('.ui-fieldset-content > .ng-untouched').click();
        cy.get('footer > .card-botoes > :nth-child(1) > .ui-button > .ui-button-text').click();
        /* ==== End Cypress Studio ==== */
    });
});