name: Run Cypress Tests

on:
  push:
    branches:
      - main  # Cambia esto si usas una rama diferente

jobs:
  test:
    runs-on: ubuntu-latest  # Usa 'windows-latest' o 'macos-latest' si prefieres otro sistema

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Esto descarga el código en la máquina de GitHub Actions

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Usa la versión de Node.js que necesites

      - name: Run Cypress tests with record
        run: |
          npx cypress run --record --key ${{ secrets.CYPRESS_RECORD_KEY }}  # Usa el secret de la clave de registro